### ISSUE TITLE
update osg container for new ngmix

### ISSUE THREAD

**Issue by esheldon** [beckermr/stackvana-docker#2]
It turns out the version we have been running had a bad bug in ngmix that came just after the tagging of v1.3.7  I wrongly thought the bug fix was in 1.3.7

I've been using this image in production, it is possible this could explain some of the incomprehensible results we have had.

**Comment by esheldon** [comment]
I also used this container for all the nersc runs.  I think we need to version them.

**Comment by beckermr** [comment]
version the containers?

**Comment by beckermr** [comment]
sure

**Comment by esheldon** [comment]
instead of just `beckermr/stackvana:latest` maybe give a version

**Comment by beckermr** [comment]
We should have both. I can add a docker autobuild to produce a tag. Also, we'll need to submit any versions we want on the osg to their repo with the tag. They pull latest which makes it easy for us to update things.
